// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpH5w6NlYYlLv4Um2SciP7cSMzHEP8iTo',
    appId: '1:448336593725:android:b76d89698990b91824fb54',
    messagingSenderId: '448336593725',
    projectId: 'staugustinechsapp',
    databaseURL: 'https://staugustinechsapp.firebaseio.com',
    storageBucket: 'staugustinechsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSoT-UfwzSU4534PoMeiV0XO7CKlzh3h8',
    appId: '1:448336593725:ios:05a44d1a022f3fe024fb54',
    messagingSenderId: '448336593725',
    projectId: 'staugustinechsapp',
    databaseURL: 'https://staugustinechsapp.firebaseio.com',
    storageBucket: 'staugustinechsapp.appspot.com',
    androidClientId: '448336593725-aitrgsn19hppn2flic1rdrgad50r74ot.apps.googleusercontent.com',
    iosClientId: '448336593725-s0fm1j92bo65uk16kmtp40dnkdif6sdf.apps.googleusercontent.com',
    iosBundleId: 'com.staugustinechs.app',
  );
}
