// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9lxJA2zchpowCJp6lUBLFVpuSB2fmeYU',
    appId: '1:679735156531:android:69dcd23d46e034d420a846',
    messagingSenderId: '679735156531',
    projectId: 'st-augustine-chs-app-dev',
    storageBucket: 'st-augustine-chs-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF1NI3BaQv-0QEdfNju8gHohnVJ6qwNhU',
    appId: '1:679735156531:ios:f907f3f98aa4288420a846',
    messagingSenderId: '679735156531',
    projectId: 'st-augustine-chs-app-dev',
    storageBucket: 'st-augustine-chs-app-dev.appspot.com',
    androidClientId: '679735156531-guohlal52e6ff0n370vvsa9ia1vfj6do.apps.googleusercontent.com',
    iosClientId: '679735156531-b1vnrsrgg6mu30hr0vnvhpirh6fb72e0.apps.googleusercontent.com',
    iosBundleId: 'com.staugustinechs.app',
  );
}
